server:
    port: 8080

logging.level.org.springframework.security: DEBUG

spring:
  application:
    name: ms-duminjum
    instance_id: 002
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
    username: root
    password: 1234
  #数据库连接池配置
    max-active: 200
    max-idle: 100
    min-idle: 50
    initial-size: 20
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    validation-query: select 1
    #每10分钟收集空闲连接，单位毫秒
    time-between-eviction-runs-millis: 600000
    #连接的最大空闲时间，单位毫秒，60分钟
    min-evictable-idle-time-millis: 3600000
    max-wait: 60000

logging:
  file: e://logs/ms-duminjun.log
  level.*: INFO

mybatis.config: classpath:mybatis-config.xml